---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-oddin
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector: 
    name: "{{ .Release.Name }}-{{ .Values.frontend.selector_name }}"
  type: ClusterIP