apiVersion: v1
kind: Service
metadata:
  name: frontend-service-oddin
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: frontend-gateway
      prefix: /
      service: frontend-service-oddin:80
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    name: "{{ .Release.Name }}-{{ .Values.frontend.selector_name }}"
