---
apiVersion: v1
kind: ConfigMap
data:
  SERVICE_BACKEND_API: nginx-api-service-clusterip
  SERVICE_FRONTEND: frontend-service-clusterip
  SERVICE_AIRFLOW:  airflow-web-service-nodeport:8080
  SERVICE_MEMCACHED: memcached-clusterip-service
  SERVICE_DGRAPH_ALPHA: 
  SERVICE_DGRAPH_ZERO: 
  SERVICE_RATEL: 
metadata:
  name: global-configmaps