---
apiVersion: v1
kind: ConfigMap
data:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
  # AIRFLOW__SENTRY__SENTRY_DNS: https://5274d3d8a24e4a6aa977467ba97dc426@sentry.io/1797836
  AIRFLOW__WEBSERVER__AUTHENTICATE: "False"
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: Never
  AIRFLOW__KUBERNETES__DAGS_VOLUME_CLAIM: airflow
  AIRFLOW__KUBERNETES__IN_CLUSTER: "True"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: juniorsntsid/airflow-docker
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: v2
metadata:
  name: airflow-cfgfile
---
apiVersion: v1
data:
  name: teste
kind: ConfigMap
metadata:
  name: airflow-gitsync