apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-deployment
spec:
  ports:
  - nodePort: 31463
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: airflow-webserver-pod
  type: NodePort
