---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      name: postgres-pod
  template:
    metadata:
      labels:
        name: postgres-pod
    spec:
      containers:
        - name: container-postgres
          image: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: dbvol
              mountPath: /var/lib/postgresql/data/pgdata
          env:
            - name: POSTGRES_PASSWORD
              value: oddin
            - name: POSTGRES_USER
              value: oddin
            - name: POSTGRES_DB
              value: oddin
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              memory: .5Gi
              cpu: .5
      volumes:
        - name: dbvol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
