---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-clusterip
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector: 
    name: frontend-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport
spec:
  ports:
  - nodePort: 31464
    port: 80
    targetPort: 80
    protocol: TCP
  selector: 
    name: frontend-pod
  type: NodePort