apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels: 
      name: frontend-pod
  template:
    metadata:
      labels:
        name: frontend-pod
    spec:
      containers:
      - name: container-frontend
        image: juniorsntsid/oddin-frontend:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: global-configmaps
        ports:
          - containerPort: 80