apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
  - nodePort: 31464
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector: 
    name: frontend-pod
  type: NodePort