---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-clusterip
  # annotations:
  #   getambassador.io/config: |
  #     ---
  #     apiVersion: ambassador/v1
  #     kind: Mapping
  #     name: frontend-gateway
  #     prefix: /caimp
  #     service: frontend-service-clusterip:80
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: frontend
  selector: 
    name: frontend-pod
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
spec:
  rules:
  - host: oddin.org
    http:
      paths:
      - path: /app
        backend:
          serviceName: frontend-service-clusterip
          servicePort: frontend