---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-clusterip
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: frontend-gateway
      prefix: /caimp/
      service: http://httpbin.org
spec:
  ports:
  - port: 30036
    targetPort: 80
    protocol: TCP
  selector: 
    name: frontend-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport
spec:
  ports:
  - nodePort: 31464
    port: 80
    targetPort: 80
    protocol: TCP
  selector: 
    name: frontend-pod
  type: NodePort