---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service-clusterip
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: backend-gateway
      prefix: /backend/
      service: backend-api-service-clusterip:9000
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector: 
    name: backend-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service-nodeport
spec:
  ports:
  - nodePort: 31466
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector: 
    name: backend-pod
  type: NodePort