---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service-clusterip
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
  selector: 
    name: backend-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service-nodeport
spec:
  ports:
  - nodePort: 31466
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector: 
    name: backend-pod
  type: NodePort