apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels: 
      name: backend-pod
  template:
    metadata:
      labels:
        name: backend-pod
    spec:
      containers:
      - name: container-backend
        image: juniorsntsid/oddin-backend-api:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        envFrom:
        - configMapRef:
            name: global-configmaps
        env:
        - name: APP_URL
          value: "http://127.0.0.1"
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: 5432
        - name: DB_DATABASE
          value: oddin
        - name: DB_USERNAME
          value: oddin
        - name: DB_PASSWORD
          value: oddin
        - name: MEMCACHED_HOST
          value: memcached-clusterip-service
        - name: MEMCACHED_PORT
          value: 11211