apiVersion: v1
kind: Service
metadata:
  name: memcached-clusterip-service
spec:
  ports:
  - port: 11211
    targetPort: 11211
    protocol: TCP
  selector: 
    name: memcached-pod-statefulset
  type: ClusterIP