---
apiVersion: v1
kind: Service
metadata:
  name: nginx-api-service-clusterip
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector: 
    name: nginx-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-api-service-nodeport
spec:
  ports:
  - nodePort: 31468
    port: 80
    targetPort: 80
    protocol: TCP
  selector: 
    name: nginx-pod
  type: NodePort