---
apiVersion: v1
kind: Service
metadata:
  name: nginx-api-service-clusterip
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: nginx-gateway
      prefix: /backend
      service: nginx-api-service-clusterip:80
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector: 
    name: nginx-pod
  type: ClusterIP