apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ambassador-pod
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: ambassador-pod
    spec:
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: ambassador
      containers:
      - name: ambassador-container
        image: quay.io/datawire/ambassador:1.2.2
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          value: default
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
