---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ambassador-cluster-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ambassador
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ambassador-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: ambassador
  namespace: default
roleRef:
  kind: ClusterRole
  name: ambassador-cluster-role
  apiGroup: rbac.authorization.k8s.io