---
apiVersion: v1
kind: ConfigMap
data:
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://oddin:oddin@postgres-airflow-service:5432/airflow
  POSTGRES_USER: oddin
  POSTGRES_PASSWORD: oddin
  POSTGRES_HOST: postgres-airflow-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: airflow
metadata:
  name: airflow-cfgfile
---
apiVersion: v1
data:
  GIT_SYNC_REPO: “https://github.com/xyz/dags-airflow"
  GIT_SYNC_BRANCH: “master”
  GIT_SYNC_ROOT: “/git”
  GIT_SYNC_DEST: “sync”
  GIT_SYNC_DEPTH: “1”
  GIT_SYNC_ONE_TIME: “false”
  GIT_SYNC_WAIT: “60”
  GIT_SYNC_USERNAME: “git_username”
  GIT_KNOWN_HOSTS: “false”
  GIT_PASSWORD: “242452”
kind: ConfigMap
metadata:
  name: airflow-gitsync