apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver-deployment
spec:
  selector:
    matchLabels:
      name: airflow-webserver-pod
  template:
    metadata:
      labels:
        name: airflow-webserver-pod
    spec:
      # - configMap:
      #     name: airflow-gitsync
      #   name: airflow-gitsync
      containers:
      - name: container-webserver-airflow
        image: juniorsntsid/airflow-docker:v2
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        args:
        - webserver
        envFrom:
        - configMapRef:
            name: airflow-cfgfile
        volumeMounts:
        - name: airflow-dags
          mountPath: /usr/local/airflow/dags
      volumes:
      - name: airflow-dags
        secret:
          secretName: nfs-secret
        persistentVolumeClaim:
          claimName: nfs
      - name: airflow-cfgfile
        configMap:
          name: airflow-cfgfile
      # - name: git-sync-clone
      #   image: k8s.gcr.io/git-sync:v3.1.2
      #   envFrom:
      #   - configMapRef:
      #       name: airflow-gitsync
      #   volumeMounts:
      #     - mountPath: /git
      #       name: airflow-dags
