apiVersion: v1
kind: Service
metadata:
  name: airflow-web-service-clusterip
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: airflow-gateway
      prefix: /airflow
      service: airflow-web-service-clusterip:80
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: airflow-webserver-pod
  type: ClusterIP
