apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: opaque
data:
  # postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6YWlyZmxvd0Bwb3N0Z3Jlcy1haXJmbG93OjU0MzIvYWlyZmxvdw==